import { ref } from "vue";

export const getAllCountries = () => {
  const countries = ref([
    { name: "Albania" },
    { name: "Argentina" },
    { name: "Armenia" },
    { name: "Australia" },
    { name: "Austria" },
    { name: "Azerbaijan" },
    { name: "Belarus" },
    { name: "Belgium" },
    { name: "Brazil" },
    { name: "Bulgaria" },
    { name: "Canada" },
    { name: "Chile" },
    { name: "China" },
    { name: "Colombia" },
    { name: "Croatia" },
    { name: "Czechia " },
    { name: "Denmark" },
    { name: "Estonia" },
    { name: "Ethiopia" },
    { name: "Finland" },
    { name: "France" },
    { name: "Germany" },
    { name: "Greece" },
    { name: "Hungary" },
    { name: "Iceland" },
    { name: "India" },
    { name: "Indonesia" },
    { name: "Iran" },
    { name: "Iraq" },
    { name: "Ireland" },
    { name: "Israel" },
    { name: "Italy" },
    { name: "Japan" },
    { name: "Kazakhstan" },
    { name: "Mexico" },
    { name: "Moldova" },
    { name: "Monaco" },
    { name: "Netherlands" },
    { name: "New Zealand" },
    { name: "Norway" },
    { name: "Philippines" },
    { name: "Poland" },
    { name: "Portugal" },
    { name: "Romania" },
    { name: "Russia" },
    { name: "Saudi Arabia" },
    { name: "Serbia" },
    { name: "Slovakia" },
    { name: "Slovenia" },
    { name: "South Africa" },
    { name: "South Korea" },
    { name: "South Sudan" },
    { name: "Spain" },
    { name: "Sweden" },
    { name: "Switzerland" },
    { name: "Syria" },
    { name: "Tajikistan" },
    { name: "Turkey" },
    { name: "Turkmenistan" },
    { name: "Ukraine" },
    { name: "UAE" },
    { name: "United Kingdom" },
    { name: "USA" },
    { name: "Uzbekistan" },
    { name: "Vietnam" },
  ]);
  return countries;
};
